### ISSUE TITLE
How to add multiple templates?

### ISSUE THREAD

**Issue by mahdimehri** [dinhtungdu/custom-elementor-source#1]
hi @dinhtungdu
your plugin is awesome

I  did read your documents but I can't understand: How to add multiple templates
for example, I have 10 JSON files 
how can add all of them in my library 
please help me 
thanks

**Comment by dinhtungdu** [comment]
Hi @mahdimehri, looking at https://github.com/dinhtungdu/custom-elementor-library-dummy-api, we have:
- One master JSON file contains information for all templates.
- In `templates`, we have JSON files for each template, which is exported using Elementor.

If you have 2 templates, you have 2 files in the `templates` folder and information about those 2 templates in the master JSON file. The same applies to as many templates as you have.

**Comment by mahdimehri** [comment]
thanks very much  &#128151;  &#128151;  &#128151;

**Comment by mahdimehri** [comment]
it not work for me 
I added 3.json in templates
and edited info.json 
add this in info.json : {
                "id": "3",
                "title": "test",
                "thumbnail": "http://localhost/Elementor/wp-content/plugins/custom-elementor-source-master/surse/library-ui-kit-cover.png",
                "tmpl_created": "1475067229",
                "author": "Elementor",
                "url": "https://library.elementor.com/education-online-courses/?utm_source=library&utm_medium=wp-dash&utm_campaign=preview",
                "type": "page",
                "subtype": "page",
                "tags": "[]",
                "menu_order": "0",
                "popularity_index": "0",
                "trend_index": "0",
                "has_page_settings": "0"
            }
but it doesn't work for me 
please help me
